library:
  customerfilename: data/customers.csv
  libraryitemfilename: data/library.csv


logging:
  file: app.log
  level:
    com:
      citylibrary: DEBUG
    org:
      springframework: ERROR
  pattern:
    console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
    file: '%d %p %c{1.} [%t] %m%n'
